SNAPSHOTER mount fs

diff --git a/snapshoter/snapshoter b/snapshoter/snapshoter
--- a/snapshoter/snapshoter
+++ b/snapshoter/snapshoter
@@ -9,9 +9,21 @@ then
 	exit $?
 fi
 
+do_clean()
+{
+	if [[ "$snapdrive" != "" ]]
+	then
+		umount $tmpdir/fs
+		rmdir $tmpdir/fs
+	fi
+	rmdir $tmpdir
+}
+
 err()
 {
-	echo -e "\e[31m\e[1m$@\e[0m"
+	echo -e "\e[31m\e[1m${@:2}\e[0m"
+	do_clean
+	exit $1
 }
 
 minus=""
@@ -51,19 +63,29 @@ then
 	read r
 	if [[ "$r" != "" ]]
 	then
-		err EXIT
-		exit 0
+		err 0 EXIT
 	fi
 	rm  $data -r
 	exit 0
 fi
 
+tmpdir="$(mktemp -d -t snapshoter-XXXXXXX)"
+chown 700 "$tmpdir"
 snapdir="/mnt/snapshot-manual"
 autosnapdir="/mnt/snapshot"
 
 . ~/snapshoter.devices
 
+
+
 [[ "$minus" == *"a"* ]] && snapdir="$autosnapdir"
+[[ "$minus" == *"a"* ]] && snapdrive="$autosnapdrive"
+if [[ "$snapdrive" != "" ]]
+then
+	mkdir $tmpdir/fs
+	mount $snapdrive $tmpdir/fs || err 100 Mount faild
+	snapdir=$tmpdir/fs
+fi
 devicedir="$snapdir/$device"
 okdir="$devicedir/ok"
 workingdir="$devicedir/working"
@@ -81,19 +103,16 @@ then
 	echo NOT SSH
 	if [[ ! -e "$from" ]]
 	then
-		err "FROM $from NOT EXIST!"
-		exit 101
+		err  101 "FROM $from NOT EXIST!"
 	fi
 	if [[ "$(ls $from)" == "" ]]
 	then
-		err "FROM $from IS EMPTY!"
-		exit 102
+		err 102 "FROM $from IS EMPTY!"
 	fi
 fi
 if [[ -e "$wto" ]] || [[ -e "$okto" ]]
 then
-	err "FILE $wto OR $okto EXIST!"
-	exit 100
+	err 100 "FILE $wto OR $okto EXIST!"
 fi
 
 to="$wto/data"
@@ -114,6 +133,7 @@ $exclude_fs && echo >> "$excludefile" "/proc"
 $exclude_fs && echo >> "$excludefile" "/run"
 $exclude_fs && echo >> "$excludefile" "/sys"
 $exclude_fs && echo >> "$excludefile" "/tmp"
+$exclude_fs && echo >> "$excludefile" "/snap"
 $exclude_mnt && echo >> "$excludefile" "/mnt"
 $exclude_aux &&  echo >> "$excludefile" "/aux"
 for h_it in $excludedir_homes
@@ -156,9 +176,8 @@ then
 	read r
 	if [[ "$r" != "" ]]
 	then
-		err EXIT
 		rm -r $wto
-		exit 0
+		err 0 EXIT
 	fi
 fi
 
@@ -170,24 +189,22 @@ echo -e -n "\e[0m"
 
 if [[ "$r" != "0" ]]
 then
-	echo
-	err RSYNC ERROR $r
-	[[ "$r" != 24 ]] && exit 1
+	echo RSYNC ERROR $r
+	[[ "$r" != 24 ]] && err 1 "RSYNC ERROR"
 fi
 if [[ "$(ls $to)" == "" ]]
 then
-	err "TO DIRECTORY $to IS EMPTY!"
-	exit 104
+	err  104 "TO DIRECTORY $to IS EMPTY!"
 fi
 echo
 echo RSYNC OK
 mv $wto $okto
 if [[ "$?" != "0" ]]
 then
-	echo FINEL MV $?
-	err 2
+	echo 2 FINEL MV $?
 fi
 echo ALL OK
+do_clean
 
 
 #rsync  \
